### ISSUE TITLE
Can not find slither command even its available

### ISSUE THREAD

**Issue by doublevkay** [trailofbits/slither-vscode#54]
Slither works fine from the terminal, but the extension still throws the following error:

### Error logs
```
⸻ Slither: Solidity static analysis framework by Trail of Bits ⸻
Error: /bin/sh: slither: command not found

Error: Slither not found:
Please verify slither is installed with the following command: "pip install slither-analyzer"
For more information, please visit: https://github.com/crytic/slither
```

### Env
- Macos 15
- Slither installed with `pipx install slither-analyzer`

**Comment by frabert** [comment]
I'm not familiar with `pipx` so this is going to be a bit of a shot in the dark, but could you try starting VSCode by running `code` from the same terminal where you can access `slither`?

**Comment by doublevkay** [comment]
It seems I had some problems with the `code` path. So after I [removed and re-added the vscode path](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line), the extension works now.

Thanks @frabert.
